shawnlaffan/biodiverse

- lib/Biodiverse/Spatial.pm
- lib/Biodiverse/SpatialConditions.pm
- t/27-Spatial.t
Tests for sp_spatial_output_passed_defq
> Issue 625 sp pass defq

- bin/create_correlogram_data.pl
- example_scripts/add_matrix_to_basedata.pl
- lib/Biodiverse/BaseData.pm
- lib/Biodiverse/BaseStruct.pm
- lib/Biodiverse/Cluster.pm
- lib/Biodiverse/Common.pm
- lib/Biodiverse/Config.pm
- lib/Biodiverse/ElementProperties.pm
- lib/Biodiverse/GUI/BasedataImport.pm
- lib/Biodiverse/GUI/MatrixImport.pm
- lib/Biodiverse/GUI/OpenDialog.pm
- lib/Biodiverse/GUI/Project.pm
- lib/Biodiverse/GUI/Tabs/Randomise.pm
- lib/Biodiverse/Index.pm
- lib/Biodiverse/Indices.pm
- lib/Biodiverse/Indices/IEI.pm
- lib/Biodiverse/Indices/Indices.pm
- lib/Biodiverse/Indices/LabelProperties.pm
- lib/Biodiverse/Matrix.pm
- lib/Biodiverse/Matrix/Base.pm
- lib/Biodiverse/Spatial.pm
- lib/Biodiverse/SpatialConditions.pm
- lib/Biodiverse/Tree.pm
- lib/Biodiverse/TreeNode.pm
- xt/mem_leak_tests/93-numlabels_mem_leaks.pl
- xt/mem_leak_tests/93-rand_mem_leaks_mk3.pl
- xt/mem_leak_tests/93-rand_mem_leaks_mk3_with_tree.pl
Use Ref::Util instead of =~ /ARRAY/ or /HASH/
> Issue 635 use ref util

- lib/Biodiverse/BaseData.pm
> Clarify column count in BaseData import error message.

- .travis.yml
- cpanfile
- lib/Biodiverse/Tree.pm
Wrt issue https://github.com/shawnlaffan/biodiverse/issues/568
Passing tests at https://travis-ci.org/cv-library/biodiverse/builds/196135806
> Adding travis CI support

- .gitignore
- .idea/workspace.xml
- lib/Biodiverse/Common.pm
- lib/Biodiverse/GUI/Dendrogram.pm
- lib/Biodiverse/GUI/Grid.pm
- lib/Biodiverse/GUI/Legend.pm
- lib/Biodiverse/GUI/MatrixGrid.pm
- lib/Biodiverse/GUI/Tabs/Spatial.pm
- lib/Biodiverse/GUI/Tabs/Tab.pm
- lib/Biodiverse/Randomise.pm
- lib/Biodiverse/Spatial.pm
- lib/Biodiverse/Tree.pm
- t/29-CANAPE.t
Merge changes for #819 onto the main branch
> Canape mk2

- .github/workflows/linux_de_locale.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
- appveyor.yml
- lib/Biodiverse/Indices/PhylogeneticRelative.pm
- lib/Biodiverse/Spatial.pm
- lib/Biodiverse/Tree.pm
- lib/Biodiverse/TreeNode.pm
- t/11-BaseData-reintegrate-after-rand.t
Updates for #819, plus some CI and other changes
> Issue 819 canape tests

- lib/Biodiverse/ReadNexus.pm
> Tree imports: Try most likely import method first

- lib/Biodiverse/Indices/PhyloCom.pm
- t/24-Indices-phylocom-nri-nti.t
> Issue 842 vpd

- lib/Biodiverse/BaseData.pm
- lib/Biodiverse/Common.pm
- lib/Biodiverse/GUI/Dendrogram.pm
- lib/Biodiverse/GUI/Grid.pm
- lib/Biodiverse/GUI/Legend.pm
- lib/Biodiverse/GUI/Tabs/Spatial.pm
- lib/Biodiverse/Randomise.pm
- t/11-BaseData-reintegrate-after-rand.t
- t/28-Randomisation.t
- t/lib/Biodiverse/TestHelpers.pm
> Issue 856 p rank, and some randomisation micro-optimisations 

- .cirrus.yml
- lib/Biodiverse/BaseData.pm
The cirrus fails are unrelated.
> Issue 859 reduce res precision

- lib/Biodiverse/RemapGuesser.pm
This means we can skip any strings that are
too long or short to possibly match within
the specified edit distance.
Closes #864
> Remaps: Index possible matches by length

- lib/Biodiverse/Matrix.pm
- t/26-Cluster2.t
> Issue 866 mx summary stats

- Makefile.PL
- bin/load_and_randomise.pl
- bin/load_and_randomise_wrapper.pl
- cpanfile
- lib/Biodiverse/BaseData.pm
- lib/Biodiverse/BaseData/Import.pm
- lib/Biodiverse/BaseStruct.pm
- lib/Biodiverse/BaseStruct/Export.pm
- lib/Biodiverse/Cluster.pm
- lib/Biodiverse/Common.pm
- lib/Biodiverse/Config.pm
- lib/Biodiverse/GUI/Export.pm
- lib/Biodiverse/GUI/GUIManager.pm
- lib/Biodiverse/GUI/Manager/BaseDatas.pm
- t/01-clone-save-reload.t
- t/02-unicode-file-names.t
- t/11-BaseData-import-feature-data.t
- t/11-BaseData-import-spreadsheet.t
- t/11-BaseData-reintegrate-after-rand.t
- t/11-BaseData.t
- t/lib/Biodiverse/TestHelpers.pm
Also removes DBD::XBase from Makefile.PL and cpanfile
Fixes #853
> Replace Path::Class and File::Spec with Path::Tiny

- lib/Biodiverse/GUI/BasedataImport.pm
> GUI: use specified sheet in spreadsheet imports

- .gitignore
- lib/Biodiverse/GUI/Dendrogram.pm
- lib/Biodiverse/GUI/Grid.pm
- lib/Biodiverse/GUI/Legend.pm
- lib/Biodiverse/GUI/Tabs/Spatial.pm
- lib/Biodiverse/GUI/Tabs/Tab.pm
- lib/Biodiverse/Indices.pm
- lib/Biodiverse/Metadata/Indices.pm
- t/23-Indices.t
Support categorical indices
The metadata structure might yet change but it works.
> Categorical indices

- lib/Biodiverse/BaseStruct.pm
- lib/Biodiverse/Indices/Phylogenetic.pm
And change the env var to control loading of Data::Recursive to
BD_NO_USE_DATA_RECURSIVE
Closes #755
> Remove usages of Panda::Lib

- lib/Biodiverse/Cluster.pm
> Cluster progress: improved precision for most similar value

- lib/Biodiverse/GUI/Manager/BaseDatas.pm
Fixes #928, with better tested code than in that issue.
> GUI: Improved value checks for bd clone with reduced resolutions

- lib/Biodiverse/Common.pm
- lib/Biodiverse/GUI/Legend.pm
- lib/Biodiverse/GUI/Manager/BaseDatas.pm
- lib/Biodiverse/Spatial.pm
- lib/Biodiverse/Tree.pm
- t/29-CANAPE.t
> More CANAPE variants

- t/00-load.t
> Tests: better feedback when alien is optional

- lib/Biodiverse/GUI/Grid.pm
- lib/Biodiverse/GUI/Overlays.pm
- lib/Biodiverse/GUI/Project.pm
> Issue 891 part2

- lib/Biodiverse/GUI/BasedataImport.pm
- lib/Biodiverse/GUI/Canvas/Grid.pm
- lib/Biodiverse/GUI/Canvas/Matrix.pm
- lib/Biodiverse/GUI/Canvas/ScreePlot.pm
- lib/Biodiverse/GUI/Tabs/Labels.pm
> GUI tweaks 20250708

- lib/Biodiverse/Tree.pm
- lib/Biodiverse/TreeNode.pm
Some additional tree caching and a slightly faster method
> Tree cache 20250719

- bin/ui/wndOverlays.ui
- lib/Biodiverse/GUI/Canvas/Grid.pm
- lib/Biodiverse/GUI/Overlays.pm
- lib/Biodiverse/GUI/Project.pm
This means we can have per-layer colours and plot more than one layer at a time.
Fixes #48 
Still need to add a re-ordering option.
> Update the overlay interface

- lib/Biodiverse/GUI/Canvas/Grid.pm
- lib/Biodiverse/GUI/Overlays.pm
And some re-ordering or the columns
> Overlays: Allow the user to set the alpha value

- lib/Biodiverse/GUI/GUIManager.pm
- lib/Biodiverse/Indices.pm
- lib/Biodiverse/Spatial.pm
Also pack the feedback into a scrolled window.
Fixes #748
> Spatial: Provide more feedback when no valid analyses

- lib/Biodiverse/GUI/Canvas.pm
- lib/Biodiverse/GUI/Canvas/Grid.pm
- lib/Biodiverse/GUI/Canvas/Matrix.pm
- lib/Biodiverse/GUI/Canvas/ScreePlot.pm
- lib/Biodiverse/GUI/Canvas/Tree.pm
If there are no data then there is no transform matrix, and several calls will otherwise die.
This happens if there is no matrix or tree plotted.
> GUI canvases: check if the canvas has data before calling events

- bin/ui/hboxClusteringPage.ui
- bin/ui/hboxLabelsPage.ui
- bin/ui/hboxSpatialPage.ui
- lib/Biodiverse/GUI/Canvas.pm
- lib/Biodiverse/GUI/Tabs/Clustering.pm
- lib/Biodiverse/GUI/Tabs/Labels.pm
- lib/Biodiverse/GUI/Tabs/Spatial.pm
- lib/Biodiverse/GUI/Tabs/SpatialMatrix.pm
- lib/Biodiverse/GUI/Tabs/Tab.pm
Allows the user to change the background colour of the map and tree panes.
> User specified canvas background colours

- .gitignore
- bin/ui/dlgExport.ui
- lib/Biodiverse/Common.pm
- lib/Biodiverse/GUI/Export.pm
- lib/Biodiverse/GUI/ParametersTable.pm
The Gtk3 change had knock-on effects such that the OK and Cancel buttons could be off-screen.
> GUI parameters table updates
