shawnlaffan/biodiverse

- lib/Biodiverse/GUI/Project.pm
When converting from ref ____ to is_arrayref, I missed a '!' in Project.pm, which broke tree imports. This fixes that issue. 
See https://github.com/shawnlaffan/biodiverse/commit/53fb2450c06510278f56d00fa959ebda4c5329c4#diff-eafa3a4ec94f973c7a23899085889bce for where error was introduced.
> Fix bug in conversion to Ref::Util

- README.md
- lib/Biodiverse/Indices/Endemism.pm
- lib/Biodiverse/Indices/GroupProperties.pm
- lib/Biodiverse/Indices/Hierarchical_Labels.pm
- lib/Biodiverse/Indices/Indices.pm
- lib/Biodiverse/Indices/LabelProperties.pm
- lib/Biodiverse/Indices/LabelPropertiesRangeWtd.pm
- lib/Biodiverse/Indices/Numeric_Labels.pm
- lib/Biodiverse/Indices/PhyloCom.pm
- lib/Biodiverse/Indices/Phylogenetic.pm
- lib/Biodiverse/Indices/PhylogeneticRelative.pm
Hello :-)
The DOI foundation recommends [this new resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). It may be a bit ironic that they would change the URL of their service, but it's now [encrypted](https://www.ssllabs.com/ssltest/analyze.html?d=doi.org). Because the old `dx` subdomain is being redirected, there is no urgent need to do anything.
However, I'd hereby like to suggest to follow the new recommendation by applying this update to all static DOI links.
Cheers!
> Hyperlink DOIs to preferred resolver

- etc/benchmark_scripts/bench_hash_sum.pl
- lib/Biodiverse/BaseData/ManageOutputs.pm
- lib/Biodiverse/Cluster.pm
- lib/Biodiverse/GUI/GUIManager.pm
- lib/Biodiverse/Indices/Phylogenetic.pm
- lib/Biodiverse/Indices/Phylogenetic/RefAlias.pm
- lib/Biodiverse/Indices/PhylogeneticRelative.pm
- lib/Biodiverse/Spatial.pm
- lib/Biodiverse/Tree.pm
- lib/Biodiverse/TreeNode.pm
- t/13-Tree.t
Includes a few other minor cleanups.
> Speed improvements for PE, RPE etc

- lib/Biodiverse/Indices/Phylogenetic.pm
- t/24-Indices-phylogenetic-local-PD.t
> Indices: local PD: Avoid errors when there are no labels on tree

- lib/Biodiverse/TreeNode.pm
- t/13-Tree.t
Fixes #877 (hopefully properly this time)
> treenode to R phylo: handle root length properly

- lib/Biodiverse/BaseData/Import.pm
The previous approach was a leftover from when GDAL did not support this method for shapefiles,
instead returning -1.
Support in GDAL was added some time ago.
The call can be updated when Geo::GDAL::FFI
provides a wrapped method.
Fixes #885
> Feature data imports: use GetFeatureCount for progress dialogue

- lib/Biodiverse/Common.pm
- lib/Biodiverse/GUI/Legend.pm
- t/29-CANAPE.t
> Add CANAPE super class

- lib/Biodiverse/Indices.pm
- lib/Biodiverse/Indices/Endemism.pm
- lib/Biodiverse/Indices/GroupProperties.pm
- lib/Biodiverse/Indices/Indices.pm
- lib/Biodiverse/Indices/LabelProperties.pm
- lib/Biodiverse/Indices/LabelPropertiesRangeWtd.pm
- lib/Biodiverse/Indices/Matrix_Indices.pm
- lib/Biodiverse/Indices/Numeric_Labels.pm
- lib/Biodiverse/Indices/PhyloCom.pm
- lib/Biodiverse/Indices/Phylogenetic.pm
- lib/Biodiverse/Indices/PhylogeneticRelative.pm
- lib/Biodiverse/Indices/Rarity.pm
- lib/Biodiverse/Metadata/Indices.pm
- t/23-Indices.t
- t/26-Cluster.t
- t/26-Cluster2.t
- t/26-RegionGrower.t
- t/28-Randomisation.t
- t/28-Randomisation2.t
- t/31-Remap.t
- t/31-RemapGuesser.t
Provides metadata for the numeric bounds of any non-categorical indices.  
Also provides these data as JSON.
There are currently no categorical indices in Biodiverse.  These can be supported if and when implemented.  (CANAPE is a compound index not generated by calls to a Biodiverse::Indices object).
Updates #889
> Indices metadata - numeric bounds

- lib/Biodiverse/Indices/PhyloCom.pm
- lib/Biodiverse/Indices/Phylogenetic.pm
- lib/Biodiverse/Tree.pm
- t/24-Indices-phylogenetic.t
Exceptions are those that return information about the tree, e.g. how many and which branches match the basedata.
Fixes #896
> Indices: Ensure branches are non-negative for most phylo calculations

- lib/Biodiverse/BaseData.pm
- lib/Biodiverse/BaseData/Import.pm
- lib/Biodiverse/Common.pm
- lib/Biodiverse/Config.pm
- lib/Biodiverse/Config/PARModules.pm
- lib/Biodiverse/Indices.pm
- lib/Biodiverse/Indices/Endemism.pm
- lib/Biodiverse/Indices/Indices.pm
- lib/Biodiverse/Indices/PhyloCom.pm
- lib/Biodiverse/Indices/Phylogenetic.pm
- lib/Biodiverse/Indices/RWTurnover.pm
- lib/Biodiverse/Metadata/Indices.pm
- t/23-Indices.t
- t/lib/Biodiverse/TestHelpers.pm
Fixes several of the issues that motivated #895
Still to do:
> Index bounds2

- lib/Biodiverse/GUI/Legend.pm
- lib/Biodiverse/GUI/Tabs/Spatial.pm
- lib/Biodiverse/GUI/Tabs/Tab.pm
> GUI Spatial tab: support branch colouring using any spatial output across the project

- lib/Biodiverse/GUI/Dendrogram.pm
- lib/Biodiverse/GUI/Grid.pm
- lib/Biodiverse/GUI/Legend.pm
- lib/Biodiverse/GUI/Tabs/Clustering.pm
- lib/Biodiverse/GUI/Tabs/Labels.pm
- lib/Biodiverse/GUI/Tabs/Outputs.pm
- lib/Biodiverse/GUI/Tabs/Randomise.pm
- lib/Biodiverse/GUI/Tabs/RegionGrower.pm
- lib/Biodiverse/GUI/Tabs/Spatial.pm
- lib/Biodiverse/GUI/Tabs/SpatialMatrix.pm
- lib/Biodiverse/GUI/Tabs/Tab.pm
Fixes a few issues with the Cluster and SpatialMatrix tabs that were missed in #893 
Also a few other general changes.  
Updates #820
> Miscellaneous legend fixes

- lib/Biodiverse/GUI/Tabs/Spatial.pm
> Issue 909 list more trees in the spatial tab tree combobox

- lib/Biodiverse/Common.pm
- lib/Biodiverse/Common/Caching.pm
- lib/Biodiverse/GUI/Dendrogram.pm
- lib/Biodiverse/GUI/Tabs/Clustering.pm
- lib/Biodiverse/GUI/Tabs/Labels.pm
- lib/Biodiverse/GUI/Tabs/Spatial.pm
- lib/Biodiverse/GUI/Tabs/Tab.pm
- lib/Biodiverse/Tree.pm
> GUI: Support eq length and range weighted tree plots

- lib/Biodiverse/GUI/Tabs/Spatial.pm
> Issue 818 spatial tab: allow highlight of dendro paths for hovered cell only

- .github/workflows/linux_de_locale.yml
- lib/Biodiverse/Randomise.pm
- lib/Biodiverse/Randomise/CurveBall.pm
- lib/Biodiverse/Randomise/IndependentSwaps.pm
- t/28-Randomisation.t
Updates #822 
Could be optimised but that can be done as a later step.
> Implement the curveball randomisation algorithm

- lib/Biodiverse/BaseData.pm
- lib/Biodiverse/BaseStruct.pm
- lib/Biodiverse/Indices/Endemism.pm
- lib/Biodiverse/Indices/HierarchicalLabels.pm
- lib/Biodiverse/Indices/Indices.pm
- lib/Biodiverse/Randomise/CurveBall.pm
- lib/Biodiverse/Spatial.pm
- t/28-Randomisation.t
First few commits are focused on _calc_abc but later commits span other parts of the system.
> A set of general optimisations

- lib/Biodiverse/BaseData.pm
- lib/Biodiverse/BaseStruct.pm
- lib/Biodiverse/Indices/Phylogenetic.pm
- lib/Biodiverse/Progress.pm
- lib/Biodiverse/Randomise.pm
- lib/Biodiverse/Randomise/CurveBall.pm
- lib/Biodiverse/Randomise/IndependentSwaps.pm
- lib/Biodiverse/Spatial.pm
- lib/Biodiverse/Tree.pm
- lib/Biodiverse/TreeNode.pm
A set of general optimisations and cleanups.
> General changes 20240212

- Makefile.PL
- cpanfile
- lib/Biodiverse/Common/ColourPalettes.pm
- lib/Biodiverse/GUI/GUIManager.pm
- lib/Biodiverse/GUI/Legend.pm
- lib/Biodiverse/GUI/Manager/BaseDatas.pm
- lib/Biodiverse/GUI/Tabs/CalculationsTree.pm
- lib/Biodiverse/Indices/Indices.pm
- lib/Biodiverse/Indices/RichnessEstimation.pm
- lib/Biodiverse/Metadata/BaseStruct.pm
- lib/Biodiverse/Metadata/Parameter.pm
- lib/Biodiverse/Metadata/Randomisation.pm
- lib/Biodiverse/Metadata/SpatialConditions.pm
- t/23-Indices.t
Updates and optimisations for the richness estimation indices,
including displaying the metadata as categories in the GUI.
And a few other minor things.
> Richness estimation 2024

- lib/Biodiverse/Cluster.pm
- lib/Biodiverse/Indices.pm
- lib/Biodiverse/Indices/Indices.pm
- lib/Biodiverse/Indices/RWTurnover.pm
- lib/Biodiverse/Matrix.pm
- lib/Biodiverse/Matrix/Base.pm
- lib/Biodiverse/Matrix/LowMem.pm
- t/25-Matrix.t
A set of general optimisations to speed up matrix creation for cluster analyses.  
Initially focused on the matrix classes but then extended to the index calculations.
> Faster cluster matrix creation

- lib/Biodiverse/Cluster.pm
- lib/Biodiverse/Common.pm
- lib/Biodiverse/Indices.pm
- lib/Biodiverse/Indices/Endemism.pm
- lib/Biodiverse/Indices/Phylogenetic.pm
- lib/Biodiverse/Indices/Phylogenetic/RefAlias.pm
- lib/Biodiverse/Randomise.pm
- lib/Biodiverse/Spatial.pm
- lib/Biodiverse/Tree.pm
- lib/Biodiverse/TreeNode.pm
- t/26-Cluster2.t
A set of optimisations to several index and related calculations.  
Summary of main changes: 
* Hierarchical calculations are now supported.  This allows cluster tree calculations to build on the child results rather than rebuilding everything for each node. 
* Several endemism calculations now re-use results where the central and whole variants will be the same. 
* Significance assessments are faster.
> Index and other optimisations 

- lib/Biodiverse/Indices.pm
- lib/Biodiverse/Indices/Endemism.pm
- lib/Biodiverse/Indices/Indices.pm
- lib/Biodiverse/Indices/LabelCounts.pm
- lib/Biodiverse/Indices/LabelProperties.pm
- lib/Biodiverse/Indices/Matrix_Indices.pm
- lib/Biodiverse/Indices/Phylogenetic.pm
- lib/Biodiverse/Indices/PhylogeneticRelative.pm
- lib/Biodiverse/Indices/Rarity.pm
- lib/Biodiverse/Metadata/Indices.pm
- t/11-BaseData-reintegrate-after-rand.t
This PR includes several optimisations.  Chief among them are:
* Implement _calc_abc_any for cases where a depending method only needs the label hash keys or element lists
* calc_abc grabs and modifies results from calc_abc2 or calc_abc3 if already run, thus saving some processing
* calc_abc2 or calc_abc3 are always run before calc_abc
* add a hierarchical _calc_abc variant for cases such as cluster node calcs where the label hashes can be generated from the child node results instead of processing the full list of terminals
* some other general index optimisations such as result sharing when nbr set 2 is empty
> More index optimisations

- lib/Biodiverse/Randomise/CurveBall.pm
We store scalar variables for the array lengths anyway so we might as well use them.
> micro-optimise rand_curveball

- lib/Biodiverse/GUI/Tabs/Spatial.pm
> Spatial tab: user control of tree branch undef colour

- lib/Biodiverse/Cluster.pm
- t/26-Cluster2.t
Otherwise we can be left with results that are no longer needed.
Fixes #924
> Cluster calcs per node: clean up existing results first

- bin/ui/wndOverlays.ui
- lib/Biodiverse/GUI/GUIManager.pm
- lib/Biodiverse/GUI/Grid.pm
- lib/Biodiverse/GUI/Overlays.pm
- lib/Biodiverse/GUI/Project.pm
> GUI: plot polygons

- lib/Biodiverse/Randomise.pm
- lib/Biodiverse/Randomise/CurveBall.pm
> GUI: Make randomisation options available to more algs

- lib/Biodiverse/GUI/ParametersTable.pm
- lib/Biodiverse/GUI/Tabs/Randomise.pm
- lib/Biodiverse/Randomise/CurveBall.pm
This hides or shows the box group labels as a function of the visibility of the constituent widgets.
If none are visible then the label is hidden.
This will improve the user experience as non-relevant labels are no longer shown.
> GUI randomisations: hide/show box-group labels

- lib/Biodiverse/Common.pm
- lib/Biodiverse/Randomise.pm
- lib/Biodiverse/Randomise/CurveBall.pm
- lib/Biodiverse/SpatialConditions.pm
- t/11-BaseData-reintegrate-after-rand.t
- t/22-SpatialConditions-main.t
- t/28-Randomisation.t
> Randomisations: Add neigbourhood swapper to rand_curveball  

- lib/Biodiverse/GUI/Project.pm
The check for complete deletion was using the hashref instead of the file name.
Fixes #960
> Fix overlay removal

- lib/Biodiverse/GUI/Canvas/Grid.pm
- lib/Biodiverse/GUI/Canvas/Matrix.pm
The previous approach stored it with the coordinates, which started to cause carry-over effects when
these were cached at the basedata level.
> GUI canvases: rework the grid colouring

- lib/Biodiverse/GUI/Canvas.pm
- lib/Biodiverse/GUI/Canvas/Grid.pm
- lib/Biodiverse/GUI/Canvas/Matrix.pm
- lib/Biodiverse/GUI/Canvas/Tree.pm
1. Remove the index from the Grid canvas.  It is not actually needed unless we have a very sparse and very large basestruct.
2. Show the rectangle when selecting.  
3. Minor updates to the Matrix selection code,
> Canvas updates

- bin/ui/hboxClusteringPage.ui
- bin/ui/hboxLabelsPage.ui
- bin/ui/hboxSpatialPage.ui
- lib/Biodiverse/GUI/Tabs/Clustering.pm
- lib/Biodiverse/GUI/Tabs/Labels.pm
- lib/Biodiverse/GUI/Tabs/Spatial.pm
- lib/Biodiverse/GUI/Tabs/SpatialMatrix.pm
- lib/Biodiverse/GUI/Tabs/Tab.pm
The old naming scheme dates back to the monolithic glade file.
Each tab is in its own file now so the names can be the same across files and the handling code simplified.
> GUI: Simplify the naming scheme for the pan/zoom widgets
